import { parseAbi } from 'viem';

/**
 * Every custom error the deployed contracts can revert with, so a failed simulation can be
 * named. The ABIs the app sends transactions with carry no error entries, and without them
 * viem reports only "reverted with the following signature:" and the raw selector — which
 * the UI cut at the colon, leaving a sentence that ended in nothing.
 *
 * The Ostium entries are every `error` declared in contracts/src/vendor/ostium/interfaces
 * (one entry per distinct signature); then OpenZeppelin's ERC20 errors, which USDW raises,
 * and the USDW faucet's CooldownActive.
 */
export const CONTRACT_ERRORS_ABI = parseAbi([
  'error NullAddr()',
  'error DelegatedActionFailed()',
  'error IsContract(address a)',
  'error NoDelegate(address a)',
  'error NotDelegate(address trader, address caller)',
  'error SignatureExpired()',
  'error InvalidSignature()',
  'error InvalidNonce()',
  'error DelegateForbidden()',
  'error DelegateReentrant()',
  'error InvalidCallData()',
  'error NotForwarder(address a)',
  'error AlreadyForwarder(address a)',
  'error OnlyTimelock(address a)',
  'error OnlyGovernance(address a)',
  'error ExecutionFailed(address target, bytes data, bytes returnData)',
  'error NotVault(address a)',
  'error NotGov(address a)',
  'error TooEarly()',
  'error WrongParams()',
  'error NotCallbacks(address a)',
  'error NotRegistryOwner(address a)',
  'error NotPairInfos(address a)',
  'error NotManager(address a)',
  'error NotGovOrManager(address a)',
  'error MaxReached()',
  'error PairNotEmpty()',
  'error NotAuthorized(address a)',
  'error GroupNotListed(uint256 index)',
  'error FeeNotListed(uint256 index)',
  'error PairNotListed(uint256 index)',
  'error PairAlreadyListed(bytes32 from, bytes32 to)',
  'error WrongTimestamp()',
  'error NotTrading(address a)',
  'error NotTimelock(address a)',
  'error NotRouter(address a)',
  'error NotContract(address a)',
  'error NotInitiated(uint256 a)',
  'error AlreadyInitiated(uint256 a)',
  'error InvalidPrice(uint256 orderId)',
  'error NotFound(bytes32 name)',
  'error HasAlreadyRole(address a)',
  'error AlreadyRegistered(bytes32 name)',
  'error IsDone()',
  'error WrongTP()',
  'error WrongSL()',
  'error IsPaused()',
  'error BelowMinLevPos()',
  'error ExposureLimits()',
  'error NotTradesUpKeep(address a)',
  'error AboveMaxAllowedCollateral()',
  'error PairNotListed(uint16 index)',
  'error WaitTimeout(uint256 orderId)',
  'error WrongLeverage(uint32 leverage)',
  'error NoTradeToTimeoutFound(uint256 orderId)',
  'error NotOpenMarketTimeoutOrder(uint256 orderId)',
  'error NotCloseMarketTimeoutOrder(uint256 orderId)',
  'error NotYourOrder(uint256 orderId, address trader)',
  'error MaxPendingMarketOrdersReached(address trader)',
  'error MaxTradesPerPairReached(address trader, uint16 pairIndex)',
  'error NoTradeFound(address trader, uint16 pairIndex, uint8 index)',
  'error NoLimitFound(address trader, uint16 pairIndex, uint8 index)',
  'error AlreadyMarketClosed(address trader, uint16 pairIndex, uint8 index)',
  'error TriggerPending(address sender, uint16 pairIndex, uint8 index)',
  'error BelowFees()',
  'error NotPriceUpKeep(address a)',
  'error NotEmptyIndex()',
  'error NotTradingOrCallbacks(address a)',
  'error NotManagerOrMaxOIKeeper(address a)',
  'error NoOpenLimitOrder(address _trader, uint16 _pairIndex, uint8 _index)',
  'error NullPrice()',
  'error NullAmount()',
  'error NoDiscount()',
  'error AboveBalance()',
  'error AboveMaxMint()',
  'error AboveMaxDeposit()',
  'error NotEnoughAssets()',
  'error MaxDailyPnlReached()',
  'error WaitNextEpochStart()',
  'error AboveWithdrawAmount()',
  'error NotMM(address a)',
  'error NotDev(address a)',
  'error NotOpenPnl(address a)',
  'error NotAllowed(address a)',
  'error DepositNotUnlocked(uint256 id)',
  'error PendingWithdrawal(address from, uint256 amount)',
  'error WrongLockDuration(uint256 duration, uint256 minLock, uint256 maxLock)',
  'error SharesOutTooHigh(uint256 shares, uint256 maxSharesOut)',
  'error AssetsInTooLow(uint256 assets, uint256 minAssetsIn)',
  'error FunctionDisabled()',
  'error DepositNotClaimable(address owner, uint32 settlementId)',
  'error WithdrawNotClaimable(address owner, uint32 settlementId)',
  'error DepositNotReclaimable(address owner, uint32 settlementId)',
  'error WithdrawNotReclaimable(address owner, uint32 settlementId)',
  'error ZeroAmount()',
  'error InsufficientBuffer()',
  'error NotAuthorizedSigner(address a)',
  'error AlreadyAuthorizedSigner(address a)',
  'error ERC20InsufficientBalance(address sender, uint256 balance, uint256 needed)',
  'error ERC20InsufficientAllowance(address spender, uint256 allowance, uint256 needed)',
  'error ERC20InvalidSender(address sender)',
  'error ERC20InvalidReceiver(address receiver)',
  'error ERC20InvalidApprover(address approver)',
  'error ERC20InvalidSpender(address spender)',
  'error CooldownActive(uint256 availableAt)',
]);

/**
 * What a trader is told for the reverts their own order can cause and that they can act on.
 * Any other contract error is shown by its name — still more useful than a selector.
 */
export const CONTRACT_ERROR_MESSAGES: Readonly<Record<string, string>> = {
  BelowFees: 'This order is too small to cover its fees. Increase the size.',
  BelowMinLevPos: "This position is below the market's minimum size once fees are taken out. Increase the size.",
  WrongLeverage: 'That leverage is outside what this market allows.',
  ExposureLimits: "This market's open-interest limit would be exceeded. Try a smaller size.",
  AboveMaxAllowedCollateral: 'That margin is above the per-trade maximum.',
  MaxPendingMarketOrdersReached: 'You already have the maximum number of orders waiting for a keeper. Wait for them to settle.',
  MaxTradesPerPairReached: 'You already hold the maximum number of positions on this market.',
  WrongTP: 'The take profit is on the wrong side of the entry price.',
  WrongSL: 'The stop loss is on the wrong side of the entry price.',
  IsPaused: 'Trading is paused right now.',
  IsDone: 'Trading on this deployment has been closed.',
  PairNotListed: 'This market is not listed.',
  TriggerPending: 'A take profit, stop loss or liquidation is already executing on this position. Try again in a moment.',
  AlreadyMarketClosed: 'A close for this position is already waiting for a keeper.',
  NoTradeFound: 'That position no longer exists — it may already have been closed.',
  NoLimitFound: 'That order no longer exists — it may already have been filled or cancelled.',
  WaitTimeout: 'This order cannot be reclaimed yet. Wait for its timeout to pass.',
  ERC20InsufficientAllowance: 'The trading allowance does not cover this order. Approve it and try again.',
};
